name: customers_app_google_play
description: لا اله الا الله
publish_to: 'Google Play'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.7.16

  # A
  animations: ^2.0.11
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0
  animated_button: ^0.2.0
  achievement_view: ^1.0.0
  animated_text_kit: ^4.2.2
  animated_splash_screen: ^1.3.0
  #avatar_glow: ^3.0.1
  #auto_direction: ^0.0.6

  # B
  badges: ^3.0.2
  bottom_bar_page_transition: ^2.0.0

  # C
  collection: ^1.17.1
  card_swiper: ^3.0.1
  carousel_slider: ^4.1.1
  cached_network_image: ^3.3.1
  country_state_city_picker: ^1.2.8
  #concentric_transition: ^1.0.3
  #confetti: ^0.7.0

  # D
  date_picker_timeline: ^1.2.5
  dotted_border: ^2.1.0
  #delayed_widget: ^1.1.1

  # E
  expandable: ^5.0.1

  # F
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.1.0
  flutter_stripe: ^10.0.0
  flutter_slidable: ^3.0.1
  flutter_screenutil: ^5.9.0
  flutter_rating_bar: ^4.0.1
  flutter_pw_validator: ^1.4.2
  flutter_native_splash: ^2.3.8
  font_awesome_flutter: ^10.7.0
  fluentui_system_icons: ^1.1.229
  flutter_local_notifications: ^16.3.2
  flutter_staggered_animations: ^1.1.1
  flutter_plugin_android_lifecycle: ^2.0.17
  #flutter_native_splash: ^2.2.17
  #firebase_ui_firestore: ^1.5.1
  #firebase_pagination: ^3.0.0
  #flutter_neumorphic: ^3.2.0
  #flutter_slimy_card: ^1.0.2
  #flutter_speed_dial: ^6.0.0
  #flutter_animate: ^4.2.0
  #flutter_mobx: ^2.0.6+5
  #future_manager: ^1.3.0

  # G
  get: ^4.6.6
  glitcheffect: ^1.1.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  google_fonts: ^4.0.4
  getwidget: ^4.0.0
  google_mobile_ads: ^4.0.0

  # H
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hexcolor: ^3.0.1

  # I
  intl: ^0.18.0
  icons_plus: ^5.0.0
  image_picker: ^1.0.7
  #in_app_update: ^4.1.4

  # J
  # K
  # L
  lottie: ^3.1.0
  liquid_pull_to_refresh: ^3.0.1

  # M
  # N
  # O
  open_settings: ^2.0.2

  # P
  provider: ^6.1.1
  path: ^1.9.0
  permission_handler: ^11.3.0
  #particles_flutter: ^0.1.4
  #pull_to_refresh: ^2.0.0
  #path_provider: ^2.0.14

  # Q
  qr_flutter: ^4.1.0

  # R
  rive: ^0.12.4

  # S
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  sn_progress_dialog: ^1.1.3
  shape_of_view_null_safe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  staggered_grid_view_flutter: ^0.0.4
  #shimmer: ^3.0.0
  #syncfusion_flutter_charts: ^20.4.44
  #syncfusion_flutter_sliders: ^21.1.35

  # T
  # U
  uuid: ^4.3.3
  url_launcher: ^6.2.5
  #upgrader: ^8.0.0

  # V
  #velocity_x: ^3.6.0

  # W
  # X
  # Y
  # Z

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

#flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 16


#flutter pub run flutter_native_splash:create
#flutter_native_splash:
#  background_image: "assets/images/splash.png"
#  android: true
#  ios: true
#  fullscreen: true

flutter:

  uses-material-design: true

  assets:
      - assets/fonts/
      - assets/fonts/Dosis/
      - assets/json/
      - assets/images/
      - assets/riveAssets/
      - assets/images/inapp/
      - assets/images/handmade/
      - assets/sounds/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts/Dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts/Dosis/Dosis-Light.ttf
        - asset: assets/fonts/Dosis/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
        - asset: assets/fonts/Dosis/Dosis-VariableFont_wght.ttf
          style: normal
          weight: 500
    - family: Monofett
      fonts:
        - asset: assets/fonts/Monofett-Regular.ttf
          style: normal

    - family: Explora
      fonts:
        - asset: assets/fonts/Explora-Regular.ttf
          style: normal

    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight-Regular.ttf
          style: normal
          weight: 100
    - family: EnglishSC
      fonts:
        - asset: assets/fonts/IMFellEnglishSC-Regular.ttf
          style: normal
          weight: 100

    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
          style: normal
          weight: 500
