// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAl0yJjMV9oNgpsOmWSoWaZEQyFMz4O3U',
    appId: '1:572399345674:web:4d432a96261d0c75b17ff3',
    messagingSenderId: '572399345674',
    projectId: 'multi-store-d5205',
    authDomain: 'multi-store-d5205.firebaseapp.com',
    storageBucket: 'multi-store-d5205.appspot.com',
    measurementId: 'G-DM67Y3F37E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFIfhSakwyV8t1dJoee7Gb82wWz34fTU',
    appId: '1:572399345674:android:7ab4a149cf9b7745b17ff3',
    messagingSenderId: '572399345674',
    projectId: 'multi-store-d5205',
    storageBucket: 'multi-store-d5205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaNNivGVEw2UXm3ksrxewJndHRwueOWBQ',
    appId: '1:572399345674:ios:0728b4388738d81ab17ff3',
    messagingSenderId: '572399345674',
    projectId: 'multi-store-d5205',
    storageBucket: 'multi-store-d5205.appspot.com',
    androidClientId: '572399345674-f07mlcr8j6mnve8hd9m8qv1epnof567m.apps.googleusercontent.com',
    iosClientId: '572399345674-et06eokh036b82faq5mupnpj6kdbol9j.apps.googleusercontent.com',
    iosBundleId: 'customersappgoogleplay.com.customersAppGooglePlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaNNivGVEw2UXm3ksrxewJndHRwueOWBQ',
    appId: '1:572399345674:ios:0728b4388738d81ab17ff3',
    messagingSenderId: '572399345674',
    projectId: 'multi-store-d5205',
    storageBucket: 'multi-store-d5205.appspot.com',
    androidClientId: '572399345674-f07mlcr8j6mnve8hd9m8qv1epnof567m.apps.googleusercontent.com',
    iosClientId: '572399345674-et06eokh036b82faq5mupnpj6kdbol9j.apps.googleusercontent.com',
    iosBundleId: 'customersappgoogleplay.com.customersAppGooglePlay',
  );
}
